name: Sync main → develop after PR merge or direct push

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Determine if we should run
        id: check
        run: |
          if [ "${GITHUB_EVENT_NAME}" = "push" ]; then
            echo "run_merge=true" >> $GITHUB_OUTPUT
          elif [ "${GITHUB_EVENT_NAME}" = "pull_request" ] && [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            echo "run_merge=true" >> $GITHUB_OUTPUT
          else
            echo "run_merge=false" >> $GITHUB_OUTPUT
      - name: Exit if not a merged PR or push
        if: ${{ steps.check.outputs.run_merge != 'true' }}
        run: echo "Nothing to do" && exit 0

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch develop branch
        run: git fetch origin develop:develop

      - name: Merge main into develop and Push
        run: |
          git checkout develop
          set +e
          git merge origin/main --no-commit --no-ff
          MERGE_STATUS=$?
          set -e
          if [ $MERGE_STATUS -ne 0 ]; then
            echo "::warning:: ❌ Conflicts detected when merging 'main' into 'develop'. Synchronization must be done manually."
            git merge --abort || true
            exit 0
          fi
          git commit -m "chore: merge main → develop [automated]"
          git push origin develop
