name: Merge main → develop

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para ver todas las ramas

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch develop branch
        run: git fetch origin develop:develop

      - name: Merge main into develop
        run: |
          git checkout develop
          set +e
          git merge origin/main --no-commit --no-ff
          MERGE_STATUS=$?
          set -e

          if [ $MERGE_STATUS -ne 0 ]; then
            echo "❌ Conflictos detectados. Debes hacer el merge manualmente."
            git merge --abort || true
            exit 1
          fi

          git commit -m "chore: merge main → develop [automated]"
          git push origin develop
