name: Sync main → develop (Custom Action)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-main-to-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create branch and push
        id: create_branch
        run: |
          BRANCH="auto/sync-main-develop-$(date +%s)"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

          git fetch origin main
          git fetch origin develop

          # Crear rama temporal basada en main
          git checkout -b $BRANCH origin/main

          # Push de la rama temporal
          git push origin $BRANCH

      - name: Create Pull Request via GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_FOR_PR }}
          BRANCH: ${{ env.BRANCH }}
        run: |
          API_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls"
          DATA=$(jq -n \
            --arg title "chore: sync main → develop [automated]" \
            --arg head "$BRANCH" \
            --arg base "develop" \
            --arg body "This PR was automatically created to sync main into develop." \
            '{title: $title, head: $head, base: $base, body: $body}')
          
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "$API_URL" \
            -d "$DATA")
          
          echo "PR Response: $RESPONSE"
