name: Sync main → develop after PR merge or direct push

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' || 
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch develop branch
        run: git fetch origin develop:develop

      - name: Merge main into develop and Push
        run: |
          git checkout develop
          set +e
          
          git merge origin/main --no-commit --no-ff
          MERGE_STATUS=$?
          
          set -e
          if [ $MERGE_STATUS -ne 0 ]; then
            echo "::warning:: ❌ Conflicts detected when merging 'main' into 'develop'. Synchronization must be done manually."
            git merge --abort || true
            exit 0
          fi
          
          git commit -m "chore: merge main → develop [automated]"
          git push origin develop