name: Sync main → develop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-main-to-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Necesitamos profundidad 0 para comparar adecuadamente las ramas
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create sync branch based on main
        id: sync_branch
        run: |
          # Nombre de la rama temporal (basada en el timestamp)
          BRANCH="auto/sync-main-develop-$(date +%s)"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          
          # Traer main y develop (asegura que tengamos las referencias actualizadas)
          git fetch origin main
          git fetch origin develop
          
          # 1. Verificar si 'develop' ya contiene todos los commits de 'main'.
          if git merge-base --is-ancestor origin/main origin/develop; then
            echo "La rama 'main' es un ancestro de 'develop'. No hay nuevos commits en 'main' para sincronizar."
            echo "Saltando la creación de rama y el Pull Request."
            exit 0
          fi

          # 2. Crear la rama temporal basada exactamente en main
          # Esto asegura que la rama temporal contenga SÓLO el estado actual de main.
          git checkout -b $BRANCH origin/main
          
          # 3. Push de la rama temporal con el contenido de main
          git push origin $BRANCH

      - name: Create Pull Request
        # Este paso solo se ejecuta si el paso anterior no salió con 'exit 0'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_FOR_PR }}
          branch: ${{ env.BRANCH }}       # rama temporal (origen del PR)
          base: develop                  # rama destino
          title: "chore: sync main → develop [automated]"
          body: "This PR was automatically created to sync main into develop."
          draft: false
          delete-branch: true